[package]
name = "mygame-render"
version = "0.1.0"
edition = "2024"

[dependencies]
lightyear.workspace = true
avian3d.workspace = true
bevy.workspace = true
serde.workspace = true
leafwing-input-manager.workspace = true

[lints]
workspace = true
